### ISSUE TITLE
Définition de set_sprite_multicolore_on() erronée

### ISSUE THREAD

**Issue by auraes** [Monos1984/happyc64#2]
Conformement à la documentation, il semblerait que contrairement à ce qui figure dans happyc64.h, la fonction se nomme `set_sprite_multicolore_on() `et non `sprite_multicolore_on()`. Il manque `set_`.

**Comment by Monos1984** [comment]
Merci Auraes. C'est le fichier h qui semble merdé. Dans le .c j'ai bien un set...
Merci.
